name: Latest GitHub Repositories
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch and update latest GitHub repos
        uses: Readme-Workflows/recent-activity@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_REPOS: 10
          COMMIT_MESSAGE: "📦 Update latest GitHub repos"
