name: README Repos List
on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:myselfakash20"
          max: 10
          start: "REPO-LIST:START"
          end: "REPO-LIST:END"
          path: README.md
          prefix: "- "
